namespace WowLogAnalyzer.Enums;
public enum CombatSubEventType
{
    Unknown = 0,

    // --- Core / System ---
    COMBAT_LOG_VERSION = 1,
    ZONE_CHANGE = 2,
    MAP_CHANGE = 3,
    COMBATANT_INFO = 4,
    ENCOUNTER_START = 5,
    ENCOUNTER_END = 6,

    // --- Melee (SWING) ---
    SWING_DAMAGE = 100,
    SWING_DAMAGE_LANDED = 101,
    SWING_MISSED = 102,

    // --- Ranged ---
    RANGE_DAMAGE = 200,
    RANGE_MISSED = 201,

    // --- Spell ---
    SPELL_CAST_START = 300,
    SPELL_CAST_SUCCESS = 301,
    SPELL_CAST_FAILED = 302,
    SPELL_DAMAGE = 303,
    SPELL_MISSED = 304,
    SPELL_HEAL = 305,
    SPELL_HEAL_ABSORBED = 306,
    SPELL_ENERGIZE = 307,
    SPELL_DRAIN = 308,
    SPELL_LEECH = 309,
    SPELL_INSTAKILL = 310,
    SPELL_INTERRUPT = 311,
    SPELL_DISPEL = 312,
    SPELL_DISPEL_FAILED = 313,
    SPELL_STOLEN = 314,
    SPELL_AURA_APPLIED = 315,
    SPELL_AURA_REMOVED = 316,
    SPELL_AURA_REFRESH = 317,
    SPELL_AURA_APPLIED_DOSE = 318,
    SPELL_AURA_REMOVED_DOSE = 319,
    SPELL_AURA_BROKEN_SPELL = 320,
    SPELL_PERIODIC_DAMAGE = 321,
    SPELL_PERIODIC_HEAL = 322,
    SPELL_PERIODIC_ENERGIZE = 323,
    SPELL_PERIODIC_DRAIN = 324,
    SPELL_PERIODIC_LEECH = 325,
    SPELL_PERIODIC_MISSED = 326,
    SPELL_ABSORBED = 327,
    SPELL_CREATE = 328,
    SPELL_SUMMON = 329,
    SPELL_RESURRECT = 330,
    SPELL_BUILDING_DAMAGE = 331,
    SPELL_BUILDING_HEAL = 332,
    SPELL_EXTRA_ATTACKS = 333,

    // --- Environmental ---
    ENVIRONMENTAL_DAMAGE = 400,
    ENVIRONMENTAL_HEAL = 401,

    // --- Damage Split / Reflect ---
    DAMAGE_SPLIT = 500,
    DAMAGE_SHIELD = 501,
    DAMAGE_SHIELD_MISSED = 502,

    // --- Unit / Death ---
    UNIT_DIED = 600,
    UNIT_DESTROYED = 601,
    UNIT_DISSIPATES = 602,
    PARTY_KILL = 603,

    // --- World / Misc ---
    WORLD_MARKER_PLACED = 700,
    WORLD_MARKER_REMOVED = 701,
    EMOTE = 702,
    ENCHANT_APPLIED = 703,
    ENCHANT_REMOVED = 704
}