// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WowLogAnalyzer.Data;

#nullable disable

namespace WowLogAnalyzer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WowLogAnalyzer.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("guid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("server");

                    b.HasKey("Id")
                        .HasName("pk_characters");

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("WowLogAnalyzer.Entities.CharacterEncounter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("character_id");

                    b.Property<int>("EncounterId")
                        .HasColumnType("integer")
                        .HasColumnName("encounter_id");

                    b.Property<int>("SpecId")
                        .HasColumnType("integer")
                        .HasColumnName("spec_id");

                    b.HasKey("Id")
                        .HasName("pk_character_encounters");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("ix_character_encounters_character_id");

                    b.HasIndex("EncounterId")
                        .HasDatabaseName("ix_character_encounters_encounter_id");

                    b.HasIndex("SpecId")
                        .HasDatabaseName("ix_character_encounters_spec_id");

                    b.ToTable("character_encounters", (string)null);
                });

            modelBuilder.Entity("WowLogAnalyzer.Entities.CombatEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("Amount")
                        .HasColumnType("double precision")
                        .HasColumnName("amount");

                    b.Property<double?>("AmountIncoming")
                        .HasColumnType("double precision")
                        .HasColumnName("amount_incoming");

                    b.Property<int?>("AmountIncomingType")
                        .HasColumnType("integer")
                        .HasColumnName("amount_incoming_type");

                    b.Property<int?>("AmountType")
                        .HasColumnType("integer")
                        .HasColumnName("amount_type");

                    b.Property<int?>("EncounterId")
                        .HasColumnType("integer")
                        .HasColumnName("encounter_id");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("event_data");

                    b.Property<int>("EventType")
                        .HasColumnType("integer")
                        .HasColumnName("event_type");

                    b.Property<int?>("FromCharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("from_character_id");

                    b.Property<string>("FromGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("from_guid");

                    b.Property<int>("LogId")
                        .HasColumnType("integer")
                        .HasColumnName("log_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<int?>("ToCharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("to_character_id");

                    b.Property<string>("ToGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_guid");

                    b.HasKey("Id")
                        .HasName("pk_combat_events");

                    b.HasIndex("EncounterId")
                        .HasDatabaseName("ix_combat_events_encounter_id");

                    b.HasIndex("FromCharacterId")
                        .HasDatabaseName("ix_combat_events_from_character_id");

                    b.HasIndex("ToCharacterId")
                        .HasDatabaseName("ix_combat_events_to_character_id");

                    b.HasIndex("LogId", "EventType", "Timestamp")
                        .HasDatabaseName("idx_combat_events_log_type_time");

                    b.ToTable("combat_events", (string)null);
                });

            modelBuilder.Entity("WowLogAnalyzer.Entities.Encounter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty");

                    b.Property<int>("EncounterId")
                        .HasColumnType("integer")
                        .HasColumnName("encounter_id");

                    b.Property<string>("EncounterName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encounter_name");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<int?>("EndCombatEventId")
                        .HasColumnType("integer")
                        .HasColumnName("end_combat_event_id");

                    b.Property<int?>("LogId")
                        .HasColumnType("integer")
                        .HasColumnName("log_id");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<int?>("StartCombatEventId")
                        .HasColumnType("integer")
                        .HasColumnName("start_combat_event_id");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.HasKey("Id")
                        .HasName("pk_encounters");

                    b.HasIndex("EndCombatEventId")
                        .HasDatabaseName("ix_encounters_end_combat_event_id");

                    b.HasIndex("LogId")
                        .HasDatabaseName("ix_encounters_log_id");

                    b.HasIndex("StartCombatEventId")
                        .HasDatabaseName("ix_encounters_start_combat_event_id");

                    b.ToTable("encounters", (string)null);
                });

            modelBuilder.Entity("WowLogAnalyzer.Entities.Guild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Server")
                        .HasColumnType("text")
                        .HasColumnName("server");

                    b.HasKey("Id")
                        .HasName("pk_guilds");

                    b.ToTable("guilds", (string)null);
                });

            modelBuilder.Entity("WowLogAnalyzer.Entities.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<int?>("GuildId")
                        .HasColumnType("integer")
                        .HasColumnName("guild_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_logs");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("ix_logs_guild_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_logs_user_id");

                    b.ToTable("logs", (string)null);
                });

            modelBuilder.Entity("WowLogAnalyzer.Entities.Spec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("class");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_specs");

                    b.ToTable("specs", (string)null);
                });

            modelBuilder.Entity("WowLogAnalyzer.Entities.SpecUniqueSpell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("SpecId")
                        .HasColumnType("integer")
                        .HasColumnName("spec_id");

                    b.Property<int>("SpellId")
                        .HasColumnType("integer")
                        .HasColumnName("spell_id");

                    b.HasKey("Id")
                        .HasName("pk_spec_unique_spells");

                    b.HasIndex("SpecId")
                        .HasDatabaseName("ix_spec_unique_spells_spec_id");

                    b.ToTable("spec_unique_spells", (string)null);
                });

            modelBuilder.Entity("WowLogAnalyzer.Entities.Spell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_spells");

                    b.ToTable("spells", (string)null);
                });

            modelBuilder.Entity("WowLogAnalyzer.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("WowLogAnalyzer.Entities.CharacterEncounter", b =>
                {
                    b.HasOne("WowLogAnalyzer.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_encounters_characters_character_id");

                    b.HasOne("WowLogAnalyzer.Entities.Encounter", "Encounter")
                        .WithMany()
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_encounters_encounters_encounter_id");

                    b.HasOne("WowLogAnalyzer.Entities.Spec", "Spec")
                        .WithMany()
                        .HasForeignKey("SpecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_encounters_specs_spec_id");

                    b.Navigation("Character");

                    b.Navigation("Encounter");

                    b.Navigation("Spec");
                });

            modelBuilder.Entity("WowLogAnalyzer.Entities.CombatEvent", b =>
                {
                    b.HasOne("WowLogAnalyzer.Entities.Encounter", "Encounter")
                        .WithMany("CombatEvents")
                        .HasForeignKey("EncounterId")
                        .HasConstraintName("fk_combat_events_encounters_encounter_id");

                    b.HasOne("WowLogAnalyzer.Entities.Character", "FromCharacter")
                        .WithMany()
                        .HasForeignKey("FromCharacterId")
                        .HasConstraintName("fk_combat_events_characters_from_character_id");

                    b.HasOne("WowLogAnalyzer.Entities.Log", "Log")
                        .WithMany("CombatEvents")
                        .HasForeignKey("LogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_combat_events_logs_log_id");

                    b.HasOne("WowLogAnalyzer.Entities.Character", "ToCharacter")
                        .WithMany()
                        .HasForeignKey("ToCharacterId")
                        .HasConstraintName("fk_combat_events_characters_to_character_id");

                    b.Navigation("Encounter");

                    b.Navigation("FromCharacter");

                    b.Navigation("Log");

                    b.Navigation("ToCharacter");
                });

            modelBuilder.Entity("WowLogAnalyzer.Entities.Encounter", b =>
                {
                    b.HasOne("WowLogAnalyzer.Entities.CombatEvent", "EndCombatEvent")
                        .WithMany()
                        .HasForeignKey("EndCombatEventId")
                        .HasConstraintName("fk_encounters_combat_events_end_combat_event_id");

                    b.HasOne("WowLogAnalyzer.Entities.Log", "Log")
                        .WithMany()
                        .HasForeignKey("LogId")
                        .HasConstraintName("fk_encounters_logs_log_id");

                    b.HasOne("WowLogAnalyzer.Entities.CombatEvent", "StartCombatEvent")
                        .WithMany()
                        .HasForeignKey("StartCombatEventId")
                        .HasConstraintName("fk_encounters_combat_events_start_combat_event_id");

                    b.Navigation("EndCombatEvent");

                    b.Navigation("Log");

                    b.Navigation("StartCombatEvent");
                });

            modelBuilder.Entity("WowLogAnalyzer.Entities.Log", b =>
                {
                    b.HasOne("WowLogAnalyzer.Entities.Guild", "Guild")
                        .WithMany("Logs")
                        .HasForeignKey("GuildId")
                        .HasConstraintName("fk_logs_guilds_guild_id");

                    b.HasOne("WowLogAnalyzer.Entities.User", "User")
                        .WithMany("Logs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_logs_users_user_id");

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WowLogAnalyzer.Entities.SpecUniqueSpell", b =>
                {
                    b.HasOne("WowLogAnalyzer.Entities.Spec", "Spec")
                        .WithMany()
                        .HasForeignKey("SpecId")
                        .HasConstraintName("fk_spec_unique_spells_specs_spec_id");

                    b.Navigation("Spec");
                });

            modelBuilder.Entity("WowLogAnalyzer.Entities.Encounter", b =>
                {
                    b.Navigation("CombatEvents");
                });

            modelBuilder.Entity("WowLogAnalyzer.Entities.Guild", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("WowLogAnalyzer.Entities.Log", b =>
                {
                    b.Navigation("CombatEvents");
                });

            modelBuilder.Entity("WowLogAnalyzer.Entities.User", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
